const MAX_HISTORY_FOR_ANALYSIS = 10;
const MAX_HISTORY_FOR_REPLY = 20;
const MAX_PREVIOUS_HISTORY_FOR_SUMMARY = 40;

const CONVO_STATES = {
  CONTAINMENT: "CONTAINMENT",
  BREAKDOWN: "BREAKDOWN",
  ATTACHMENT_TO_BOT: "ATTACHMENT_TO_BOT",
  MISUNDERSTANDING: "MISUNDERSTANDING",
  CONGRUENCE_TEST: "CONGRUENCE_TEST",
  SOLUTION_REQUEST: "SOLUTION_REQUEST",
  INFO_REQUEST: "INFO_REQUEST",
  STAGNATION: "STAGNATION",
  INTELLECTUALIZATION: "INTELLECTUALIZATION",
  MINIMIZATION: "MINIMIZATION",
  SILENCE: "SILENCE",
  OPENING: "OPENING",
  EXPLORATION: "EXPLORATION",
  NONE: "NONE"
};

module.exports = {
  MAX_HISTORY_FOR_ANALYSIS,
  MAX_HISTORY_FOR_REPLY,
  MAX_PREVIOUS_HISTORY_FOR_SUMMARY,
  CONVO_STATES
};